/*
 * FirstEncounter1View.java
 *
 * Created on 2007/11/02, 10:43
 */

package cancer.document;

import open.dolphin.client.RegexConstrainedDocument;

/**
 *
 * @author  kazm
 */
public class FirstEncounter1View extends javax.swing.JPanel {
    
    /** Creates new form FirstEncounter1View */
    public FirstEncounter1View() {
        initComponents();
    }

    public javax.swing.JTextField getJTextField11() {
        return jTextField11;
    }

    public javax.swing.JTextField getJTextField13() {
        return jTextField13;
    }

    public javax.swing.JTextField getMealRank() {
        return mealRank;
    }

    public javax.swing.JTextField getMetastatic1() {
        return metastatic1;
    }

    public javax.swing.JTextField getMetastatic2() {
        return metastatic2;
    }

    public javax.swing.JTextField getMetastatic3() {
        return metastatic3;
    }

    public javax.swing.JTextField getMetastatic4() {
        return metastatic4;
    }

    public javax.swing.JTextField getMindRank() {
        return mindRank;
    }

    public javax.swing.JTextArea getPastHistory() {
        return pastHistory;
    }

    public javax.swing.JTextField getRecorded() {
        return recorded;
    }

    public javax.swing.JTextField getSleepRank() {
        return sleepRank;
    }

    public javax.swing.JTextArea getSubjectiveSymptom() {
        return subjectiveSymptom;
    }

    public javax.swing.JTextField getTissueType() {
        return tissueType;
    }
    
    public javax.swing.JTextField getTotsuRank() {
        return totsuRank;
    }

    public javax.swing.JTextField getUnderstanding() {
        return understanding;
    }

    public javax.swing.JRadioButton getARadio() {
        return aRadio;
    }

    public javax.swing.JRadioButton getBRadio() {
        return bRadio;
    }

    public javax.swing.JRadioButton getCRadio() {
        return cRadio;
    }

    public javax.swing.JRadioButton getFourRadio() {
        return fourRadio;
    }

    public javax.swing.JRadioButton getKankaikiRadio() {
        return kankaikiRadio;
    }

    public javax.swing.JRadioButton getOneRadio() {
        return oneRadio;
    }

    public javax.swing.JRadioButton getSaihatuRadio() {
        return saihatuRadio;
    }

    public javax.swing.JRadioButton getSyohatuRadio() {
        return syohatuRadio;
    }

    public javax.swing.JRadioButton getThreeRadio() {
        return threeRadio;
    }

    public javax.swing.JRadioButton getTmkiRadio() {
        return tmkiRadio;
    }

    public javax.swing.JRadioButton getTwoRadio() {
        return twoRadio;
    }

    public javax.swing.JRadioButton getZeroRadio() {
        return zeroRadio;
    }

    public javax.swing.JRadioButton getZoakukiRadio() {
        return zoakukiRadio;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        recorded = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        metastatic1 = new javax.swing.JTextField();
        metastatic2 = new javax.swing.JTextField();
        metastatic3 = new javax.swing.JTextField();
        metastatic4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tissueType = new javax.swing.JTextField();
        aRadio = new javax.swing.JRadioButton();
        bRadio = new javax.swing.JRadioButton();
        cRadio = new javax.swing.JRadioButton();
        understanding = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        stageCombo = new javax.swing.JComboBox();
        tCombo = new javax.swing.JComboBox();
        nCombo = new javax.swing.JComboBox();
        mCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        syohatuRadio = new javax.swing.JRadioButton();
        saihatuRadio = new javax.swing.JRadioButton();
        kankaikiRadio = new javax.swing.JRadioButton();
        zoakukiRadio = new javax.swing.JRadioButton();
        tmkiRadio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        zeroRadio = new javax.swing.JRadioButton();
        oneRadio = new javax.swing.JRadioButton();
        twoRadio = new javax.swing.JRadioButton();
        threeRadio = new javax.swing.JRadioButton();
        fourRadio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        totsuRank = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sleepRank = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mindRank = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mealRank = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectiveSymptom = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pastHistory = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        diseaseCombo = new javax.swing.JComboBox();

        jTextField11.setText("jTextField11");

        jTextField13.setText("jTextField13");

        jLabel1.setText("ãLç⁄ì˙:");

        recorded.setColumns(10);
        recorded.setFont(new java.awt.Font("SansSerif", 0, 12));
        recorded.setToolTipText("âEÉNÉäÉbÉNÇ≈ÉJÉåÉìÉ_Å[Ç™É|ÉbÉvÉAÉbÉvÇµÇ‹Ç∑ÅB");
        recorded.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel2.setText("ïa ñº:");

        jLabel3.setText("Mtastatic Site:");

        metastatic1.setFont(new java.awt.Font("SansSerif", 0, 12));
        metastatic1.setMargin(new java.awt.Insets(1, 2, 1, 2));

        metastatic2.setFont(new java.awt.Font("SansSerif", 0, 12));
        metastatic2.setMargin(new java.awt.Insets(1, 2, 1, 2));

        metastatic3.setFont(new java.awt.Font("SansSerif", 0, 12));
        metastatic3.setMargin(new java.awt.Insets(1, 2, 1, 2));

        metastatic4.setFont(new java.awt.Font("SansSerif", 0, 12));
        metastatic4.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel4.setText("ëgêDå^:");

        tissueType.setFont(new java.awt.Font("SansSerif", 0, 12));
        tissueType.setMargin(new java.awt.Insets(1, 2, 1, 2));

        buttonGroup1.add(aRadio);
        aRadio.setText("A");
        aRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(bRadio);
        bRadio.setText("B");
        bRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(cRadio);
        cRadio.setText("C");
        cRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        understanding.setFont(new java.awt.Font("SansSerif", 0, 12));
        understanding.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel5.setText("óùâìx:");

        jLabel6.setText("TNMï™óﬁ:");

        jLabel7.setText("T");

        jLabel17.setText("N");

        jLabel18.setText("M");

        jLabel19.setText("Stage");

        stageCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "IA", "IB", "II", "IIIA", "IIIB", "IV" }));

        tCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "X" }));

        nCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "X" }));

        mCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "X" }));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(7, 7, 7)
                .add(tCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel17)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(jLabel19)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stageCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(jLabel19)
                    .add(stageCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(tCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(mCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup2.add(syohatuRadio);
        syohatuRadio.setText("èâî≠");
        syohatuRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(saihatuRadio);
        saihatuRadio.setText("çƒî≠");
        saihatuRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(kankaikiRadio);
        kankaikiRadio.setText("ä∞âä˙");
        kankaikiRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(zoakukiRadio);
        zoakukiRadio.setText("ëùà´ä˙");
        zoakukiRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(tmkiRadio);
        tmkiRadio.setText("TMä˙");
        tmkiRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(syohatuRadio)
                .add(19, 19, 19)
                .add(saihatuRadio)
                .add(17, 17, 17)
                .add(kankaikiRadio)
                .add(18, 18, 18)
                .add(zoakukiRadio)
                .add(18, 18, 18)
                .add(tmkiRadio)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(syohatuRadio)
                .add(saihatuRadio)
                .add(kankaikiRadio)
                .add(zoakukiRadio)
                .add(tmkiRadio))
        );

        jLabel8.setText("èâêféûèÛãµ:");

        buttonGroup3.add(zeroRadio);
        zeroRadio.setText("0");
        zeroRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup3.add(oneRadio);
        oneRadio.setText("1");
        oneRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup3.add(twoRadio);
        twoRadio.setText("2");
        twoRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup3.add(threeRadio);
        threeRadio.setText("3");
        threeRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup3.add(fourRadio);
        fourRadio.setText("4");
        fourRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(zeroRadio)
                .add(36, 36, 36)
                .add(oneRadio)
                .add(35, 35, 35)
                .add(twoRadio)
                .add(50, 50, 50)
                .add(threeRadio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .add(37, 37, 37)
                .add(fourRadio)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(zeroRadio)
                .add(threeRadio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(twoRadio)
                .add(fourRadio)
                .add(oneRadio))
        );

        jLabel9.setText("èâêféûPS:");

        jLabel10.setText("·uí… (0-10)");

        totsuRank.setColumns(3);
        totsuRank.setDocument(new RegexConstrainedDocument("[0-9]*"));
        totsuRank.setFont(new java.awt.Font("SansSerif", 0, 12));
        totsuRank.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel11.setText("êáñ∞ (0-10)");

        sleepRank.setColumns(3);
        sleepRank.setDocument(new RegexConstrainedDocument("[0-9]*"));
        sleepRank.setFont(new java.awt.Font("SansSerif", 0, 12));
        sleepRank.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel12.setText("ãCï™ (0-10)");

        mindRank.setColumns(3);
        mindRank.setDocument(new RegexConstrainedDocument("[0-9]*"));
        mindRank.setFont(new java.awt.Font("SansSerif", 0, 12));
        mindRank.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel13.setText("êHéñ (0-10)");

        mealRank.setColumns(3);
        mealRank.setDocument(new RegexConstrainedDocument("[0-9]*"));
        mealRank.setFont(new java.awt.Font("SansSerif", 0, 12));
        mealRank.setMargin(new java.awt.Insets(1, 2, 1, 2));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(totsuRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(mindRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel11)
                        .add(18, 18, 18)
                        .add(sleepRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(mealRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(new java.awt.Component[] {mealRank, mindRank, sleepRank, totsuRank}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totsuRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(jLabel11)
                    .add(sleepRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(mealRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(mindRank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)))
        );

        jLabel14.setText("èâêféûQOL:");

        subjectiveSymptom.setColumns(20);
        subjectiveSymptom.setFont(new java.awt.Font("SansSerif", 0, 12));
        subjectiveSymptom.setLineWrap(true);
        subjectiveSymptom.setRows(5);
        subjectiveSymptom.setMargin(new java.awt.Insets(1, 2, 1, 2));
        jScrollPane1.setViewportView(subjectiveSymptom);

        pastHistory.setColumns(20);
        pastHistory.setFont(new java.awt.Font("SansSerif", 0, 12));
        pastHistory.setLineWrap(true);
        pastHistory.setRows(5);
        pastHistory.setMargin(new java.awt.Insets(1, 2, 1, 2));
        jScrollPane2.setViewportView(pastHistory);

        jLabel15.setText("é©äoè«èÛ:");

        jLabel16.setText("ä˘âùó:");

        diseaseCombo.setEditable(true);
        diseaseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "êHìπÇ™ÇÒ", "à›Ç™ÇÒ", "ëÂí∞Ç™ÇÒ", "äÃëüÇ™ÇÒ", "í_îXÇ™ÇÒ", "‰XëüÇ™ÇÒ", "ì˚Ç™ÇÒ", "éïâ»ÅEå˚ço", "ì™ËÚïîÇ™ÇÒ", "óëëÉÇ™ÇÒ", "éqã{ËÚÇ™ÇÒ", "éqã{ì‡ñåÇ™ÇÒ", "êtç◊ñEÇ™ÇÒ", "‰N„˜Ç™ÇÒ", "ëOóßëBÇ™ÇÒ", "ê∏ëÉéÓ·á", "îxÇ™ÇÒÅEècäuéÓ·á", "çúÅEìÓïîéÓä‡", "îÁïÜÇ™ÇÒ", "à´ê´çïêFéÓ", "î]éÓ·á", "îíååïa", "à´ê´ÉäÉìÉpéÓ" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel8)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel14))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(recorded, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(aRadio)
                                .add(19, 19, 19)
                                .add(bRadio)
                                .add(21, 21, 21)
                                .add(cRadio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(understanding, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 352, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, diseaseCombo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, tissueType)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(metastatic1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                        .add(metastatic3))
                                    .add(16, 16, 16)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(metastatic4)
                                        .add(metastatic2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(72, Short.MAX_VALUE)
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {metastatic1, metastatic2, metastatic3, metastatic4}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {jScrollPane1, jScrollPane2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(recorded, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(diseaseCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(metastatic1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(metastatic2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(metastatic3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(metastatic4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jLabel3)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(tissueType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(aRadio)
                    .add(cRadio)
                    .add(jLabel5)
                    .add(bRadio)
                    .add(understanding, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jLabel14))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(jLabel15))
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jLabel16))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aRadio;
    private javax.swing.JRadioButton bRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cRadio;
    private javax.swing.JComboBox diseaseCombo;
    private javax.swing.JRadioButton fourRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JRadioButton kankaikiRadio;
    private javax.swing.JComboBox mCombo;
    private javax.swing.JTextField mealRank;
    private javax.swing.JTextField metastatic1;
    private javax.swing.JTextField metastatic2;
    private javax.swing.JTextField metastatic3;
    private javax.swing.JTextField metastatic4;
    private javax.swing.JTextField mindRank;
    private javax.swing.JComboBox nCombo;
    private javax.swing.JRadioButton oneRadio;
    private javax.swing.JTextArea pastHistory;
    private javax.swing.JTextField recorded;
    private javax.swing.JRadioButton saihatuRadio;
    private javax.swing.JTextField sleepRank;
    private javax.swing.JComboBox stageCombo;
    private javax.swing.JTextArea subjectiveSymptom;
    private javax.swing.JRadioButton syohatuRadio;
    private javax.swing.JComboBox tCombo;
    private javax.swing.JRadioButton threeRadio;
    private javax.swing.JTextField tissueType;
    private javax.swing.JRadioButton tmkiRadio;
    private javax.swing.JTextField totsuRank;
    private javax.swing.JRadioButton twoRadio;
    private javax.swing.JTextField understanding;
    private javax.swing.JRadioButton zeroRadio;
    private javax.swing.JRadioButton zoakukiRadio;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getDiseaseCombo() {
        return diseaseCombo;
    }

    public javax.swing.JComboBox getMCombo() {
        return mCombo;
    }

    public javax.swing.JComboBox getNCombo() {
        return nCombo;
    }

    public javax.swing.JComboBox getStageCombo() {
        return stageCombo;
    }

    public javax.swing.JComboBox getTCombo() {
        return tCombo;
    }   
}
