/*
 * NewKarteFrame.java
 *
 * Created on 2007/11/10, 23:48
 */

package cancer.document;

/**
 *
 * @author  kazm
 */
public class NewKarteFrame extends javax.swing.JFrame {
    
    /** Creates new form NewKarteFrame */
    public NewKarteFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        newBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        addPvtBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("êVä≥ìoò^");
        setName("newKarteFrame"); // NOI18N

        jPanel1.add(progressBar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        newBtn.setText("jButton1");
        newBtn.setToolTipText("êVãKì¸óÕÉtÉHÅ[ÉÄÇï\é¶ÇµÇ‹Ç∑ÅB");
        newBtn.setMargin(new java.awt.Insets(5, 5, 5, 5));
        newBtn.setName("newBtn"); // NOI18N
        jPanel2.add(newBtn);

        modifyBtn.setText("jButton2");
        modifyBtn.setToolTipText("ÉfÅ[É^ÇèCê≥ÇµÇ‹Ç∑ÅB");
        modifyBtn.setMargin(new java.awt.Insets(5, 5, 5, 5));
        modifyBtn.setName("modifyBtn"); // NOI18N
        jPanel2.add(modifyBtn);

        addBtn.setText("jButton3");
        addBtn.setToolTipText("ìoò^ÇµÇ‹Ç∑ÅB");
        addBtn.setMargin(new java.awt.Insets(5, 5, 5, 5));
        addBtn.setName("addBtn"); // NOI18N
        jPanel2.add(addBtn);

        addPvtBtn.setText("jButton4");
        addPvtBtn.setToolTipText("ìoò^ãyÇ—éÛïtÇçsÇ¢Ç‹Ç∑ÅB");
        addPvtBtn.setMargin(new java.awt.Insets(5, 5, 5, 5));
        addPvtBtn.setName("addPvtBtn"); // NOI18N
        jPanel2.add(addPvtBtn);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addPvtBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JButton newBtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getAddBtn() {
        return addBtn;
    }

    public javax.swing.JButton getAddPvtBtn() {
        return addPvtBtn;
    }

    public javax.swing.JButton getModifyBtn() {
        return modifyBtn;
    }

    public javax.swing.JButton getNewBtn() {
        return newBtn;
    }

    public javax.swing.JProgressBar getProgressBar() {
        return progressBar;
    }

    public javax.swing.JScrollPane getScrollPane() {
        return scrollPane;
    }
    
}
