/*
 * LetterReply2.java
 *
 * Created on 2008/10/15, 15:06
 */

package open.dolphin.client;

/**
 *
 * @author  kazm
 */
public class LetterReplyView2 extends Panel2 {

    /** Creates new form LetterReply2 */
    public LetterReplyView2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientHospital = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        clientDept = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clientDoctor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        visited = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informedContent = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        confirmed = new javax.swing.JTextField();
        consultantAddress = new javax.swing.JTextField();
        consultantTelephone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        consultantHospital = new javax.swing.JTextField();
        consultantDoctor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patientBirthday = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(open.dolphin.client.Dolphin.class).getContext().getResourceMap(LetterReplyView2.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        clientHospital.setText(resourceMap.getString("clientHospital.text")); // NOI18N
        clientHospital.setName("clientHospital"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        clientDept.setText(resourceMap.getString("clientDept.text")); // NOI18N
        clientDept.setName("clientDept"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        clientDoctor.setText(resourceMap.getString("clientDoctor.text")); // NOI18N
        clientDoctor.setName("clientDoctor"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        visited.setText(resourceMap.getString("visited.text")); // NOI18N
        visited.setToolTipText(resourceMap.getString("visited.toolTipText")); // NOI18N
        visited.setName("visited"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        informedContent.setColumns(20);
        informedContent.setLineWrap(true);
        informedContent.setRows(5);
        informedContent.setName("informedContent"); // NOI18N
        jScrollPane1.setViewportView(informedContent);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        confirmed.setEditable(false);
        confirmed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        confirmed.setText(resourceMap.getString("confirmed.text")); // NOI18N
        confirmed.setName("confirmed"); // NOI18N

        consultantAddress.setEditable(false);
        consultantAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consultantAddress.setText(resourceMap.getString("consultantAddress.text")); // NOI18N
        consultantAddress.setName("consultantAddress"); // NOI18N

        consultantTelephone.setEditable(false);
        consultantTelephone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consultantTelephone.setText(resourceMap.getString("consultantTelephone.text")); // NOI18N
        consultantTelephone.setName("consultantTelephone"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        consultantHospital.setEditable(false);
        consultantHospital.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consultantHospital.setText(resourceMap.getString("consultantHospital.text")); // NOI18N
        consultantHospital.setName("consultantHospital"); // NOI18N

        consultantDoctor.setEditable(false);
        consultantDoctor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consultantDoctor.setText(resourceMap.getString("consultantDoctor.text")); // NOI18N
        consultantDoctor.setName("consultantDoctor"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        patientName.setEditable(false);
        patientName.setText(resourceMap.getString("patientName.text")); // NOI18N
        patientName.setName("patientName"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        patientBirthday.setEditable(false);
        patientBirthday.setText(resourceMap.getString("patientBirthday.text")); // NOI18N
        patientBirthday.setName("patientBirthday"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel12)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel10)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(clientDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel3))
                                    .add(clientHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(clientDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel4))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jLabel11)
                                .add(confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(consultantAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 361, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createSequentialGroup()
                                    .add(jLabel16)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(consultantTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(consultantHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createSequentialGroup()
                                    .add(jLabel17)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(consultantDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jLabel18))
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 460, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(patientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel7)
                                .add(2, 2, 2)
                                .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8)
                                .add(4, 4, 4)
                                .add(visited, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9))))
                    .add(layout.createSequentialGroup()
                        .add(222, 222, 222)
                        .add(jLabel1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(clientHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(clientDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(clientDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(visited, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10)
                .add(7, 7, 7)
                .add(jLabel11)
                .add(7, 7, 7)
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(consultantAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(consultantTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(consultantHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(consultantDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(jLabel17))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientDept;
    private javax.swing.JTextField clientDoctor;
    private javax.swing.JTextField clientHospital;
    private javax.swing.JTextField confirmed;
    private javax.swing.JTextField consultantAddress;
    private javax.swing.JTextField consultantDoctor;
    private javax.swing.JTextField consultantHospital;
    private javax.swing.JTextField consultantTelephone;
    private javax.swing.JTextArea informedContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientBirthday;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField visited;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getClientDept() {
        return clientDept;
    }

    public void setClientDept(javax.swing.JTextField clientDept) {
        this.clientDept = clientDept;
    }

    public javax.swing.JTextField getClientDoctor() {
        return clientDoctor;
    }

    public void setClientDoctor(javax.swing.JTextField clientDoctor) {
        this.clientDoctor = clientDoctor;
    }

    public javax.swing.JTextField getClientHospital() {
        return clientHospital;
    }

    public void setClientHospital(javax.swing.JTextField clientHospital) {
        this.clientHospital = clientHospital;
    }

    public javax.swing.JTextField getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(javax.swing.JTextField confirmed) {
        this.confirmed = confirmed;
    }

    public javax.swing.JTextField getConsultantAddress() {
        return consultantAddress;
    }

    public void setConsultantAddress(javax.swing.JTextField consultantAddress) {
        this.consultantAddress = consultantAddress;
    }

    public javax.swing.JTextField getConsultantDoctor() {
        return consultantDoctor;
    }

    public void setConsultantDoctor(javax.swing.JTextField consultantDoctor) {
        this.consultantDoctor = consultantDoctor;
    }

    public javax.swing.JTextField getConsultantHospital() {
        return consultantHospital;
    }

    public void setConsultantHospital(javax.swing.JTextField consultantHospital) {
        this.consultantHospital = consultantHospital;
    }

    public javax.swing.JTextField getConsultantTelephone() {
        return consultantTelephone;
    }

    public void setConsultantTelephone(javax.swing.JTextField consultantTelephone) {
        this.consultantTelephone = consultantTelephone;
    }

    public javax.swing.JTextArea getInformedContent() {
        return informedContent;
    }

    public void setInformedContent(javax.swing.JTextArea informedContent) {
        this.informedContent = informedContent;
    }

    public javax.swing.JTextField getPatientBirthday() {
        return patientBirthday;
    }

    public void setPatientBirthday(javax.swing.JTextField patientBirthday) {
        this.patientBirthday = patientBirthday;
    }

    public javax.swing.JTextField getPatientName() {
        return patientName;
    }

    public void setPatientName(javax.swing.JTextField patientName) {
        this.patientName = patientName;
    }

    public javax.swing.JTextField getVisited() {
        return visited;
    }

    public void setVisited(javax.swing.JTextField visited) {
        this.visited = visited;
    }


}
