package open.dolphin.client;

import open.dolphin.client.Panel2;

/**
 *
 */
public class LetterView extends Panel2 {
    
    /** Creates new form NewJPanel */
    public LetterView() {
        initComponents();
    }

    public javax.swing.JTextField getAddress() {
        return address;
    }

    public javax.swing.JTextField getCDept() {
        return cDept;
    }

    public javax.swing.JTextField getCDoctor() {
        return cDoctor;
    }

    public javax.swing.JTextField getCHospital() {
        return cHospital;
    }

    public javax.swing.JTextArea getClinicalCourse() {
        return clinicalCourse;
    }

    public javax.swing.JTextField getDisease() {
        return disease;
    }

    public javax.swing.JTextField getKanjya() {
        return kanjya;
    }

    public javax.swing.JTextArea getMedication() {
        return medication;
    }

    public javax.swing.JTextField getMyHospital() {
        return myHospital;
    }

    public javax.swing.JTextField getMyName() {
        return myName;
    }

    public javax.swing.JTextArea getPastFamily() {
        return pastFamily;
    }

    public javax.swing.JTextField getPatientAge() {
        return patientAge;
    }

    public javax.swing.JTextField getPatientBirthday() {
        return patientBirthday;
    }

    public javax.swing.JTextField getPatientGender() {
        return patientGender;
    }

    public javax.swing.JTextField getPatientName() {
        return patientName;
    }

    public javax.swing.JTextField getPurpose() {
        return purpose;
    }

    public javax.swing.JTextArea getRemarks() {
        return remarks;
    }

    public javax.swing.JTextField getTelephone() {
        return telephone;
    }
    
    public javax.swing.JLabel getConfirmed() {
        return confirmed;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cHospital = new javax.swing.JTextField();
        cDept = new javax.swing.JTextField();
        cDoctor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myHospital = new javax.swing.JTextField();
        myName = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        patientGender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        patientBirthday = new javax.swing.JTextField();
        patientAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        disease = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        purpose = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        clinicalCourse = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        medication = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        remarks = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        pastFamily = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        kanjya = new javax.swing.JTextField();
        confirmed = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cHospital.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cHospital.setText("紹介先病院名");
        cHospital.setBorder(null);
        cHospital.setMargin(new java.awt.Insets(5, 5, 4, 4));
        cHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHospitalActionPerformed(evt);
            }
        });

        cDept.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cDept.setText("紹介先診療科名");
        cDept.setBorder(null);
        cDept.setMargin(new java.awt.Insets(5, 5, 4, 4));
        cDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeptActionPerformed(evt);
            }
        });

        cDoctor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cDoctor.setText("紹介先先生名");
        cDoctor.setBorder(null);
        cDoctor.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel1.setText("病院");

        jLabel2.setText("科");

        jLabel3.setText("先生");

        myHospital.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        myHospital.setBorder(null);
        myHospital.setMargin(new java.awt.Insets(5, 5, 4, 4));

        myName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        myName.setBorder(null);
        myName.setMargin(new java.awt.Insets(5, 5, 4, 4));

        address.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        address.setBorder(null);
        address.setMargin(new java.awt.Insets(5, 5, 4, 4));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        telephone.setBorder(null);
        telephone.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel4.setText("電 話");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 24));
        jLabel6.setText("患者紹介状");

        jLabel7.setText("患者氏名");

        patientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        patientName.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel8.setText("性別");

        patientGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        patientGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        patientGender.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel9.setText("生年月日");

        patientBirthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        patientBirthday.setMargin(new java.awt.Insets(5, 5, 4, 4));

        patientAge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        patientAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        patientAge.setMargin(new java.awt.Insets(5, 5, 4, 4));
        patientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAgeActionPerformed(evt);
            }
        });

        jLabel10.setText("歳");

        jLabel11.setText("主訴又は病名・病状");

        disease.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        disease.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel12.setText("紹介目的");

        purpose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        purpose.setMargin(new java.awt.Insets(5, 5, 4, 4));
        purpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeActionPerformed(evt);
            }
        });

        jLabel13.setText("症状経過/検査結果/治療経過");

        clinicalCourse.setColumns(20);
        clinicalCourse.setLineWrap(true);
        clinicalCourse.setRows(5);
        clinicalCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        clinicalCourse.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel14.setText("現在の処方");

        medication.setColumns(20);
        medication.setRows(5);
        medication.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        medication.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel15.setText("備 考");

        remarks.setColumns(20);
        remarks.setLineWrap(true);
        remarks.setRows(5);
        remarks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        remarks.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel16.setText("既往症/家族歴");

        pastFamily.setColumns(20);
        pastFamily.setRows(5);
        pastFamily.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pastFamily.setMargin(new java.awt.Insets(5, 5, 4, 4));

        jLabel17.setText("殿をご紹介申し上げます。ご高診お願い致します。");

        kanjya.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        kanjya.setBorder(null);
        kanjya.setMargin(new java.awt.Insets(5, 5, 4, 4));

        confirmed.setText("  年  月  日");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 394, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(address, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 201, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(cDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, kanjya)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(cHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel17)
                                .add(jLabel1)
                                .add(jLabel2)
                                .add(jLabel3)))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(392, 392, 392)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                                    .add(myName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(36, 36, 36)
                                    .add(myHospital, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))))
                .add(51, 51, 51))
            .add(layout.createSequentialGroup()
                .add(277, 277, 277)
                .add(jLabel6)
                .addContainerGap(295, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(68, 68, 68)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel14)
                        .addContainerGap())
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(jLabel13)
                            .addContainerGap())
                        .add(layout.createSequentialGroup()
                            .add(jLabel12)
                            .addContainerGap())
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, clinicalCourse, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(disease, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel11)
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                        .add(jLabel7)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(patientName))
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                        .add(jLabel9)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(layout.createSequentialGroup()
                                                        .add(patientAge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(jLabel10))
                                                    .add(layout.createSequentialGroup()
                                                        .add(jLabel8)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(patientGender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                            .add(purpose)))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel16)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(layout.createSequentialGroup()
                                                .add(jLabel4)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(telephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(pastFamily, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(4, 4, 4))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(medication, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel15)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 249, Short.MAX_VALUE))
                                        .add(remarks, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))
                            .add(51, 51, 51)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(53, 53, 53)
                .add(jLabel6)
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(cHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(cDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(cDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel17)
                            .add(kanjya, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(8, 8, 8)
                        .add(myHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(myName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(address, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(telephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4)))
                    .add(layout.createSequentialGroup()
                        .add(106, 106, 106)
                        .add(confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLabel8)
                    .add(patientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(patientGender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jLabel10)
                    .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(patientAge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(disease, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(purpose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pastFamily, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clinicalCourse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jLabel15))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(medication, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(remarks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {address, cDept, cDoctor, cHospital, disease, kanjya, myHospital, myName, patientAge, patientBirthday, patientGender, patientName, purpose, telephone}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void cHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cHospitalActionPerformed

    private void cDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDeptActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void purposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeActionPerformed

    private void patientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientAgeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField cDept;
    private javax.swing.JTextField cDoctor;
    private javax.swing.JTextField cHospital;
    private javax.swing.JTextArea clinicalCourse;
    private javax.swing.JLabel confirmed;
    private javax.swing.JTextField disease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kanjya;
    private javax.swing.JTextArea medication;
    private javax.swing.JTextField myHospital;
    private javax.swing.JTextField myName;
    private javax.swing.JTextArea pastFamily;
    private javax.swing.JTextField patientAge;
    private javax.swing.JTextField patientBirthday;
    private javax.swing.JTextField patientGender;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField purpose;
    private javax.swing.JTextArea remarks;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables

}