/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Baka.java
 *
 * Created on 2009/05/09, 9:13:54
 */

package open.dolphin.order;

/**
 *
 * @author kushiro
 */
public class RpView extends javax.swing.JPanel implements IRpView {

    /** Creates new form Baka */
    public RpView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        setTable = new javax.swing.JTable();
        usageCheck = new javax.swing.JCheckBox();
        medicineCheck = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        stampNameField = new javax.swing.JTextField();
        inRadio = new javax.swing.JRadioButton();
        outRadio = new javax.swing.JRadioButton();
        okCntBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        rtCheck = new javax.swing.JCheckBox();
        usageCombo = new javax.swing.JComboBox();
        countField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        tonyoChk = new javax.swing.JCheckBox();
        partialChk = new javax.swing.JCheckBox();
        temporalChk = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 11, 11));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        infoLabel.setText("info"); // NOI18N

        setTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        setTable.setToolTipText("セット内容は Drag & Drop で順番を入れ替えることができます。"); // NOI18N
        jScrollPane1.setViewportView(setTable);

        usageCheck.setText("用法"); // NOI18N
        usageCheck.setToolTipText("セットに用法があればチェックされます。"); // NOI18N
        usageCheck.setEnabled(false);

        medicineCheck.setText("薬剤"); // NOI18N
        medicineCheck.setToolTipText("薬剤がセットにあればチェックされます。"); // NOI18N
        medicineCheck.setEnabled(false);

        jLabel2.setText("セット名"); // NOI18N

        stampNameField.setBackground(new java.awt.Color(255, 255, 0));
        stampNameField.setToolTipText("セット名を編集します。"); // NOI18N

        inRadio.setText("院内"); // NOI18N
        inRadio.setToolTipText("院内処方の時選択します。"); // NOI18N

        outRadio.setText("院外"); // NOI18N
        outRadio.setToolTipText("院外処方の時選択します。"); // NOI18N

        okCntBtn.setToolTipText("セットをカルテに展開し継続します。"); // NOI18N
        okCntBtn.setPreferredSize(new java.awt.Dimension(29, 29));

        okBtn.setToolTipText("セットをカルテに展開し終了します。"); // NOI18N
        okBtn.setPreferredSize(new java.awt.Dimension(29, 29));

        clearBtn.setToolTipText("セット内容をクリアします。"); // NOI18N
        clearBtn.setPreferredSize(new java.awt.Dimension(29, 29));

        deleteBtn.setToolTipText("選択した項目を削除します。"); // NOI18N
        deleteBtn.setPreferredSize(new java.awt.Dimension(29, 29));

        searchTextField.setToolTipText("検索したい医薬品名を入力します。"); // NOI18N

        rtCheck.setText("RT"); // NOI18N
        rtCheck.setToolTipText("チェックすると入力中にリアルタイムで検索します。"); // NOI18N

        usageCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "用法選択", "内服１回等(100)", "内服２回等(200)", "内服３回等(300)", "内服４回等(400)", "点眼等(500,700)", "塗布等(600)", "頓用等(800)", "吸入等(900)", "全て" }));
        usageCombo.setToolTipText("用法を検索します。"); // NOI18N

        countField.setToolTipText("検索結果の件数を表示します。"); // NOI18N

        jLabel4.setText("件数"); // NOI18N

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(searchResultTable);

        tonyoChk.setText("頓用"); // NOI18N
        tonyoChk.setToolTipText("頓用のときチェックしてください"); // NOI18N

        partialChk.setText("部分一致"); // NOI18N
        partialChk.setToolTipText("部分一致検索をします。"); // NOI18N

        temporalChk.setText("臨時"); // NOI18N
        temporalChk.setToolTipText("臨時処方の時チェックします。"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(rtCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stampNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(outRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tonyoChk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temporalChk)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(partialChk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usageCombo, 0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(countField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okCntBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medicineCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usageCheck))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usageCheck)
                        .addComponent(medicineCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(stampNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inRadio)
                        .addComponent(outRadio)
                        .addComponent(tonyoChk)
                        .addComponent(temporalChk))
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okCntBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rtCheck)
                        .addComponent(partialChk)
                        .addComponent(usageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(countField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField countField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JRadioButton inRadio;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox medicineCheck;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton okCntBtn;
    private javax.swing.JRadioButton outRadio;
    private javax.swing.JCheckBox partialChk;
    private javax.swing.JCheckBox rtCheck;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable setTable;
    private javax.swing.JTextField stampNameField;
    private javax.swing.JCheckBox temporalChk;
    private javax.swing.JCheckBox tonyoChk;
    private javax.swing.JCheckBox usageCheck;
    private javax.swing.JComboBox usageCombo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the clearBtn
     */
    public javax.swing.JButton getClearBtn() {
        return clearBtn;
    }

    /**
     * @return the countField
     */
    public javax.swing.JTextField getCountField() {
        return countField;
    }

    /**
     * @return the deleteBtn
     */
    public javax.swing.JButton getDeleteBtn() {
        return deleteBtn;
    }

    /**
     * @return the inRadio
     */
    public javax.swing.JRadioButton getInRadio() {
        return inRadio;
    }

    /**
     * @return the infoLabel
     */
    public javax.swing.JLabel getInfoLabel() {
        return infoLabel;
    }

    /**
     * @return the medicineCheck
     */
    public javax.swing.JCheckBox getMedicineCheck() {
        return medicineCheck;
    }

    /**
     * @return the okBtn
     */
    public javax.swing.JButton getOkBtn() {
        return okBtn;
    }

    /**
     * @return the okCntBtn
     */
    public javax.swing.JButton getOkCntBtn() {
        return okCntBtn;
    }

    /**
     * @return the outRadio
     */
    public javax.swing.JRadioButton getOutRadio() {
        return outRadio;
    }

    /**
     * @return the rtCheck
     */
    public javax.swing.JCheckBox getRtCheck() {
        return rtCheck;
    }

    /**
     * @return the searchResultTable
     */
    public javax.swing.JTable getSearchResultTable() {
        return searchResultTable;
    }

    /**
     * @return the searchTextField
     */
    public javax.swing.JTextField getSearchTextField() {
        return searchTextField;
    }

    /**
     * @return the setTable
     */
    public javax.swing.JTable getSetTable() {
        return setTable;
    }

    /**
     * @return the stampNameField
     */
    public javax.swing.JTextField getStampNameField() {
        return stampNameField;
    }

    /**
     * @return the usageCheck
     */
    public javax.swing.JCheckBox getUsageCheck() {
        return usageCheck;
    }

    /**
     * @return the usageCombo
     */
    public javax.swing.JComboBox getUsageCombo() {
        return usageCombo;
    }

    public javax.swing.JCheckBox getTonyoChk() {
        return tonyoChk;
    }

    /**
     * @return the partialChk
     */
    public javax.swing.JCheckBox getPartialChk() {
        return partialChk;
    }

    public javax.swing.JCheckBox getTemporalChk() {
        return temporalChk;
    }

}
