/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package open.dolphin.project;

/**
 *
 * @author kazushi
 */
public class SendMmlView extends javax.swing.JPanel {

    /**
     * Creates new form SendMmlView
     */
    public SendMmlView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendMmlChk = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        sendMmlDirField = new javax.swing.JTextField();
        sendMmlSelectionBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sendMml23Radio = new javax.swing.JRadioButton();
        sendMml3Radio = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("MML出力"));

        sendMmlChk.setText("カルテの保存時にMML出力を行う");

        jLabel1.setText("出力先ディレクトリ:");

        sendMmlSelectionBtn.setText("選択...");

        jLabel2.setText("バージョン:");

        sendMml23Radio.setText("2.3");

        sendMml3Radio.setText("3.0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(sendMmlChk))
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(sendMmlDirField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(sendMmlSelectionBtn))
                            .add(layout.createSequentialGroup()
                                .add(sendMml23Radio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(sendMml3Radio)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(sendMmlChk)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(sendMmlDirField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sendMmlSelectionBtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(sendMml23Radio)
                    .add(sendMml3Radio))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton sendMml23Radio;
    private javax.swing.JRadioButton sendMml3Radio;
    private javax.swing.JCheckBox sendMmlChk;
    private javax.swing.JTextField sendMmlDirField;
    private javax.swing.JButton sendMmlSelectionBtn;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JRadioButton getSendMml23Radio() {
        return sendMml23Radio;
    }

    public javax.swing.JRadioButton getSendMml3Radio() {
        return sendMml3Radio;
    }

    public javax.swing.JCheckBox getSendMmlChk() {
        return sendMmlChk;
    }

    public javax.swing.JTextField getSendMmlDirField() {
        return sendMmlDirField;
    }

    public javax.swing.JButton getSendMmlSelectionBtn() {
        return sendMmlSelectionBtn;
    }

}
