/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package open.dolphin.project;

/**
 *
 * @author kazushi
 */
public class SendKartePDFView extends javax.swing.JPanel {

    /**
     * Creates new form SendMmlView
     */
    public SendKartePDFView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendKartePDFChk = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        sendKartePDFDirField = new javax.swing.JTextField();
        sendKartePDFSelectionBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("カルテPDF出力"));

        sendKartePDFChk.setText("カルテの保存時にPDF出力を行う");

        jLabel1.setText("出力先ディレクトリ:");

        sendKartePDFSelectionBtn.setText("選択...");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(sendKartePDFChk))
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sendKartePDFDirField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sendKartePDFSelectionBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(sendKartePDFChk)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(sendKartePDFDirField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sendKartePDFSelectionBtn))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox sendKartePDFChk;
    private javax.swing.JTextField sendKartePDFDirField;
    private javax.swing.JButton sendKartePDFSelectionBtn;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JCheckBox getSendKartePDFChk() {
        return sendKartePDFChk;
    }

    public javax.swing.JTextField getSendKartePDFDirField() {
        return sendKartePDFDirField;
    }

    public javax.swing.JButton getSendKartePDFSelectionBtn() {
        return sendKartePDFSelectionBtn;
    }
}
