/*
 * LetterReply2.java
 *
 * Created on 2008/10/15, 15:06
 */

package open.dolphin.letter;

import open.dolphin.client.Panel2;

/**
 *
 * @author  kazm
 */
public class Reply2View extends Panel2 {

    /** Creates new form LetterReply2 */
    public Reply2View() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientHospital = new javax.swing.JTextField();
        clientDept = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clientDoctor = new javax.swing.JTextField();
        atesakiLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        visited = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informedContent = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        confirmed = new javax.swing.JTextField();
        consultantAddress = new javax.swing.JTextField();
        consultantTelephone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        consultantHospital = new javax.swing.JTextField();
        consultantDoctor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patientBirthday = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jLabel1.setText("ご　報　告（フォーム）"); // NOI18N

        jLabel3.setText("科"); // NOI18N

        clientDoctor.setToolTipText("設定の紹介状等で、敬称を選択できます"); // NOI18N

        atesakiLbl.setText("先生　御机下"); // NOI18N

        jLabel5.setText("拝啓"); // NOI18N

        jLabel6.setText("時下ますますご清祥の段、お慶び申し上げます。"); // NOI18N

        visited.setEditable(false);
        visited.setToolTipText("右クリックでカレンダーから入力できます。PDF作成時、ハイフォンは漢字の年月日に変換されます。"); // NOI18N

        jLabel9.setText("に受診されました。"); // NOI18N

        jLabel10.setText("下記ご報告させていただきます。"); // NOI18N

        informedContent.setColumns(20);
        informedContent.setLineWrap(true);
        informedContent.setRows(5);
        jScrollPane1.setViewportView(informedContent);

        jLabel12.setText("所見等"); // NOI18N

        confirmed.setEditable(false);
        confirmed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        consultantAddress.setEditable(false);
        consultantAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        consultantTelephone.setEditable(false);
        consultantTelephone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setText("電話"); // NOI18N

        consultantHospital.setEditable(false);
        consultantHospital.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        consultantDoctor.setEditable(false);
        consultantDoctor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setText("担当"); // NOI18N

        jLabel18.setText("印"); // NOI18N

        patientName.setEditable(false);

        jLabel7.setText("殿（生年月日:"); // NOI18N

        patientBirthday.setEditable(false);

        jLabel8.setText("）、"); // NOI18N

        jLabel11.setText("敬具"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(consultantHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createSequentialGroup()
                                    .add(jLabel17)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(consultantDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jLabel18))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(412, 412, 412)
                                        .add(jLabel11))
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel12)
                                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 460, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(layout.createSequentialGroup()
                                    .add(jLabel16)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(consultantTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(consultantAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 361, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(clientDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel3))
                            .add(clientHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(clientDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(atesakiLbl))
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(layout.createSequentialGroup()
                                .add(patientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel7)
                                .add(2, 2, 2)
                                .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8))
                            .add(layout.createSequentialGroup()
                                .add(visited, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10))))
                    .add(layout.createSequentialGroup()
                        .add(211, 211, 211)
                        .add(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clientHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(clientDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(clientDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(atesakiLbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(visited, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(jLabel10))
                .add(10, 10, 10)
                .add(jLabel11)
                .add(4, 4, 4)
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8)
                .add(consultantAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(consultantTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(consultantHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(consultantDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(jLabel17))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atesakiLbl;
    private javax.swing.JTextField clientDept;
    private javax.swing.JTextField clientDoctor;
    private javax.swing.JTextField clientHospital;
    private javax.swing.JTextField confirmed;
    private javax.swing.JTextField consultantAddress;
    private javax.swing.JTextField consultantDoctor;
    private javax.swing.JTextField consultantHospital;
    private javax.swing.JTextField consultantTelephone;
    private javax.swing.JTextArea informedContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientBirthday;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField visited;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getClientDept() {
        return clientDept;
    }

    public void setClientDept(javax.swing.JTextField clientDept) {
        this.clientDept = clientDept;
    }

    public javax.swing.JTextField getClientDoctor() {
        return clientDoctor;
    }

    public void setClientDoctor(javax.swing.JTextField clientDoctor) {
        this.clientDoctor = clientDoctor;
    }

    public javax.swing.JTextField getClientHospital() {
        return clientHospital;
    }

    public void setClientHospital(javax.swing.JTextField clientHospital) {
        this.clientHospital = clientHospital;
    }

    public javax.swing.JTextField getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(javax.swing.JTextField confirmed) {
        this.confirmed = confirmed;
    }

    public javax.swing.JTextField getConsultantAddress() {
        return consultantAddress;
    }

    public void setConsultantAddress(javax.swing.JTextField consultantAddress) {
        this.consultantAddress = consultantAddress;
    }

    public javax.swing.JTextField getConsultantDoctor() {
        return consultantDoctor;
    }

    public void setConsultantDoctor(javax.swing.JTextField consultantDoctor) {
        this.consultantDoctor = consultantDoctor;
    }

    public javax.swing.JTextField getConsultantHospital() {
        return consultantHospital;
    }

    public void setConsultantHospital(javax.swing.JTextField consultantHospital) {
        this.consultantHospital = consultantHospital;
    }

    public javax.swing.JTextField getConsultantTelephone() {
        return consultantTelephone;
    }

    public void setConsultantTelephone(javax.swing.JTextField consultantTelephone) {
        this.consultantTelephone = consultantTelephone;
    }

    public javax.swing.JTextArea getInformedContent() {
        return informedContent;
    }

    public void setInformedContent(javax.swing.JTextArea informedContent) {
        this.informedContent = informedContent;
    }

    public javax.swing.JTextField getPatientBirthday() {
        return patientBirthday;
    }

    public void setPatientBirthday(javax.swing.JTextField patientBirthday) {
        this.patientBirthday = patientBirthday;
    }

    public javax.swing.JTextField getPatientName() {
        return patientName;
    }

    public void setPatientName(javax.swing.JTextField patientName) {
        this.patientName = patientName;
    }

    public javax.swing.JTextField getVisited() {
        return visited;
    }

    public void setVisited(javax.swing.JTextField visited) {
        this.visited = visited;
    }

    public javax.swing.JLabel getAtesakiLbl() {
        return atesakiLbl;
    }


}
