/*
 * DocumentHistoryView.java
 *
 * Created on 2007/11/29, 16:10
 */

package open.dolphin.client;

/**
 *
 * @author  kazm
 */
public class DocumentHistoryView extends javax.swing.JPanel {
    
    /** Creates new form DocumentHistoryView */
    public DocumentHistoryView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cntLbl = new javax.swing.JLabel();
        docTypeCombo = new javax.swing.JComboBox();
        periodCombo = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setName("table"); // NOI18N
        jScrollPane1.setViewportView(table);

        cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(open.dolphin.client.Dolphin.class).getContext().getResourceMap(DocumentHistoryView.class);
        cntLbl.setText(resourceMap.getString("cntLbl.text")); // NOI18N
        cntLbl.setName("cntLbl"); // NOI18N

        docTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "カルテ", "紹介状・返書" }));
        docTypeCombo.setName("docTypeCombo"); // NOI18N

        periodCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1年", "2年", "3年", "4年", "5年", "全て" }));
        periodCombo.setName("periodCombo"); // NOI18N
        periodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodComboActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(docTypeCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(periodCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cntLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(docTypeCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(periodCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cntLbl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void periodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodComboActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cntLbl;
    private javax.swing.JComboBox docTypeCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox periodCombo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getCntLbl() {
        return cntLbl;
    }

    public javax.swing.JComboBox getDocTypeCombo() {
        return docTypeCombo;
    }

    public javax.swing.JComboBox getExtractCombo() {
        return periodCombo;
    }

    public javax.swing.JTable getTable() {
        return table;
    }
}
