/*
 * LDAPViewer.java
 *
 * Created on 2002/05/17, 22:53
 */

package jp.ac.kumamoto_u.kuh.fc.jsato.swing_beans;

import java.awt.*;
import java.io.*;
import java.util.*;

import jp.ac.kumamoto_u.kuh.fc.jsato.math_mml.*;

import netscape.ldap.*;

import javax.swing.*;
import javax.swing.tree.*;
import javax.swing.event.*;

/**
 *
 * @author  medinfo
 */
public class LDAPViewer extends javax.swing.JFrame {
    private String startH = "<html><p><div align='center'><table border>" + 
        "<tr bgcolor='blue'><th>Attribute</th><th>Value</th></tr>";
    private String endH = "</table></div></p></html>";
    
    private String makeRow(String att, String val) {
        return "<tr><td>" + att + "</td><td>" + val + "</td></tr>";
    }
    
    /** Creates new form LDAPViewer */
    public LDAPViewer() {
        initComponents();
        
        jLabel1.setText( startH + endH );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lDAPLoginBean1 = new jp.ac.kumamoto_u.kuh.fc.jsato.swing_beans.LDAPLoginBean();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));
        
        lDAPLoginBean1.setBaseDN("o=digital-globe");
        lDAPLoginBean1.setBindDN("cn=Directory Manager,o=digital-globe");
        jPanel3.add(lDAPLoginBean1);
        
        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        jPanel3.add(jButton1);
        
        jPanel1.add(jPanel3);
        
        jScrollPane1.setMaximumSize(new java.awt.Dimension(491, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(491, 160));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(491, 160));
        jPanel1.add(jScrollPane1);
        
        jScrollPane3.setMaximumSize(new java.awt.Dimension(491, 32767));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(491, 160));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(491, 160));
        jPanel1.add(jScrollPane3);
        
        getContentPane().add(jPanel1);
        
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 22));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 3));
        jScrollPane2.setViewportView(jLabel1);
        
        jPanel2.add(jScrollPane2);
        
        jScrollPane4.setMinimumSize(new java.awt.Dimension(300, 22));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 3));
        jScrollPane4.setViewportView(jLabel2);
        
        jPanel2.add(jScrollPane4);
        
        getContentPane().add(jPanel2);
        
        pack();
    }//GEN-END:initComponents

    JTree tree = null;
    DefaultMutableTreeNode root = null;
    DefaultMutableTreeNode currNode = null;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        conn = getConnection();
        if (conn == null) return;
        System.out.println("Connection was established.");
        
        // entry point of the shared directory
        String fromDN=/*"ou=Special Users," + */"ou=Library, " + lDAPLoginBean1.getBaseDN();
        System.out.println(fromDN);
        traverseTopDirectory(fromDN);
        
        disconnectLDAP();
    }//GEN-LAST:event_jButton1ActionPerformed

    private LDAPConnection conn = null;
    
    public synchronized LDAPConnection getConnection() {
        if (conn != null && conn.isConnected()) {
            return conn;
        }
        
        try {
            conn = new LDAPConnection();
            lDAPLoginBean1.updateProperties();
            conn.connect(
                lDAPLoginBean1.getHost(),
                lDAPLoginBean1.getPort(),
                lDAPLoginBean1.getBindDN(),
                lDAPLoginBean1.getPassword());
            return conn;
        } catch (LDAPException e) {
            System.out.println(e.toString());
            return null;
        }
    }
    
    public synchronized void disconnectLDAP() {
        if (conn != null && conn.isConnected()) {
            try {
                conn.disconnect();
                conn = null;
            } catch (LDAPException e) {
                System.out.println(e.toString());
            }
        }
    }
    
    private String labelText = "";
    
    public void readEntry(String findDN) {
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return;
        }

        LDAPEntry foundEntry = null;
        try {
            foundEntry = conn.read(findDN);
        } catch ( LDAPException e ) {
            /*
            switch( e.getLDAPResultCode() ) {
                case e.NO_SUCH_OBJECT:
                    System.out.println( "The specified entry does not exist." );
                    break;
                case e.LDAP_PARTIAL_RESULTS:
                    System.out.println( "Entry served by a different LDAP server." );
                    break;
                case e.INSUFFICIENT_ACCESS_RIGHTS:
                    System.out.println( "You do not have the access rights to perform this operation." );
                    break;
                default:
                    System.out.println( "Error number: " + e.getLDAPResultCode() );
                    System.out.println( "Could not read the specified entry." );
                    break;
            }
             */
            return;
        }

        //System.out.println( "Found the specified entry." );
        
        labelText = startH;
        printStringValues(foundEntry);
        labelText = labelText + endH;
        jLabel1.setText(labelText);
    }
    
    public void readContents(String findDN) {
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return;
        }

        LDAPEntry foundEntry = null;
        try {
            foundEntry = conn.read(findDN);
        } catch ( LDAPException e ) {
            /*
            switch( e.getLDAPResultCode() ) {
                case e.NO_SUCH_OBJECT:
                    System.out.println( "The specified entry does not exist." );
                    break;
                case e.LDAP_PARTIAL_RESULTS:
                    System.out.println( "Entry served by a different LDAP server." );
                    break;
                case e.INSUFFICIENT_ACCESS_RIGHTS:
                    System.out.println( "You do not have the access rights to perform this operation." );
                    break;
                default:
                    System.out.println( "Error number: " + e.getLDAPResultCode() );
                    System.out.println( "Could not read the specified entry." );
                    break;
            }
             */
            return;
        }

        //System.out.println( "Found the specified entry." );
        
        labelText = startH;
        printStringValues2(foundEntry);
        labelText = labelText + endH;
        jLabel2.setText(labelText);
    }
    
    public void printStringValues(LDAPEntry findEntry) {
        LDAPAttributeSet findAttrs = findEntry.getAttributeSet();
        Enumeration enumAttrs = findAttrs.getAttributes();
        
        while ( enumAttrs.hasMoreElements()) {
           LDAPAttribute anAttr = (LDAPAttribute)enumAttrs.nextElement();
           String attrName = anAttr.getName();
           Enumeration enumVals = anAttr.getStringValues();
           if (enumVals != null) {
              while ( enumVals.hasMoreElements() ) {
                 String aVal = (String)enumVals.nextElement();
                 System.out.println(attrName + ": " + aVal);
                 
                 labelText = labelText + makeRow(attrName, aVal);
              }
           }
        }
    }
    
    public void printStringValues2(LDAPEntry findEntry) {
        LDAPAttributeSet findAttrs = findEntry.getAttributeSet();
        Enumeration enumAttrs = findAttrs.getAttributes();
        
        while ( enumAttrs.hasMoreElements()) {
           LDAPAttribute anAttr = (LDAPAttribute)enumAttrs.nextElement();
           String attrName = anAttr.getName();
           if (attrName.equals("jpegPhoto")) {
                System.out.println("JPEG: =============================================");
                byte[] imageData = null;
                Enumeration enumVals = anAttr.getByteValues();
                if (enumVals != null) {
                    while ( enumVals.hasMoreElements() ) {
                     imageData = (byte[])enumVals.nextElement();
                     if (imageData != null) {
                         System.out.println(attrName + ": " + "JPEG DATA:-)");
                         labelText = labelText + makeRow(attrName, "JPEG DATA:-)");
                         break;
                     }
                    }
                }
                
                if (imageData != null) {
                    Image img = Toolkit.getDefaultToolkit().createImage(imageData);
                    System.out.println("Image was created.");
                    jLabel1.setIcon(new ImageIcon(img));
                }
           } else {
               Enumeration enumVals = anAttr.getStringValues();
               if (enumVals != null) {
                  while ( enumVals.hasMoreElements() ) {
                     String aVal = (String)enumVals.nextElement();
                     System.out.println(attrName + ": " + aVal);
                     labelText = labelText + makeRow(attrName, aVal);
                  }
               }
            }
        }
    }

    private int level = 0;
    
    public boolean hasChildren(String dn) {
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return false;
        }
        
        String[] attrs = null;
        LDAPSearchResults results = null;
        try {
            results = ld.search(dn, netscape.ldap.LDAPConnection.SCOPE_ONE, "(objectclass=*)", attrs, false);
        } catch (LDAPException e) {
            //System.out.println("*** Directory was not found.");
            return false;
        }
        
        if ( results.hasMoreElements() == false ) {
            //System.out.println("*** Directory was not found.");
            return false;
        }
        
        return true;
    }
    
    public String getDescription(LDAPEntry entry) {
        String val = "";
        LDAPAttribute anAttr = entry.getAttribute("description");
        if (anAttr.getStringValues() != null) {
            val = (String)anAttr.getStringValues().nextElement();
        }
        return val;
    }
    
    public void traverseDirectory(String dn) {
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return;
        }
        
        //----------------------------------------------------
        String[] attrs = {"ou","uid","description"};//null;
        //----------------------------------------------------
        LDAPSearchResults results = null;
        try {
            results = ld.search(dn, netscape.ldap.LDAPConnection.SCOPE_ONE, "(objectclass=*)", attrs, false);
        } catch (LDAPException e) {
            //System.out.println("*** Directory was not found.");
            return;
        }
        
        if ( results.hasMoreElements() == false ) {
            //System.out.println("*** Directory was not found.");
            return;
        }
        
        LDAPEntry entry = null;
        String baseDN = null;
        while ( results.hasMoreElements() ) { 
            try {
                entry = (LDAPEntry)results.next();
                baseDN = entry.getDN();
                System.out.println("Level " + level + " ---- " + baseDN);
                
                if (hasChildren(baseDN)) {
                    //------------------------------------------------------
                    String name = getDescription(entry) + "<>" + baseDN;
                    DefaultMutableTreeNode node = new DefaultMutableTreeNode(name);
                    currNode.add(node);
                    currNode = node;
                    //------------------------------------------------------

                    printStringValues(entry);

                    ++level;
                    traverseDirectory(baseDN);
                    --level;

                    //---------------------------------
                    currNode = (DefaultMutableTreeNode)currNode.getParent();
                    //---------------------------------
                }
            } catch (LDAPException e) {
                //System.out.println("*** Couldn't get entry of search result.");
                return;
            }
        }
    }
    
    JTable table = null;
    
    public int countLeaves(String dn) {
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return 0;
        }
        
        //----------------------------------------------------
        String[] attrs = {"uid","cn","sn","description"};//null;
        //----------------------------------------------------
        LDAPSearchResults results = null;
        try {
            results = ld.search(dn, netscape.ldap.LDAPConnection.SCOPE_ONE, "(objectclass=*)", attrs, false);
        } catch (LDAPException e) {
            //System.out.println("*** Directory was not found.");
            return 0;
        }
        
        if ( results.hasMoreElements() == false ) {
            //System.out.println("*** Directory was not found.");
            return 0;
        }
        
        LDAPEntry entry = null;
        String baseDN = null;
        int cnt = 0;
        while (results.hasMoreElements()) { 
            try {
                entry = (LDAPEntry)results.next();
                baseDN = entry.getDN();
                if (false == hasChildren(baseDN)) {
                    ++cnt;
                }
            } catch (LDAPException e) {
                return 0;
            }
        }      

        return cnt;
    }
    
    public void readLeaves(String dn) {
        // count the number of leaves in the directory: dn
        int cnt = countLeaves(dn);
        System.out.println("readLeaves(): Number of leaves: " + cnt);
        
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return;
        }
        
        //----------------------------------------------------
        String[] attrs = {"uid","cn","sn","description"};
        //----------------------------------------------------
        LDAPSearchResults results = null;
        try {
            results = ld.search(dn, netscape.ldap.LDAPConnection.SCOPE_ONE, "(objectclass=*)", attrs, false);
        } catch (LDAPException e) {
            //System.out.println("*** Directory was not found.");
            return;
        }
        
        if (results.hasMoreElements() == false) {
            //System.out.println("*** Directory was not found.");
            return;
        }
        
        //===========================
        String[] columnNames = {"DN", "€–Ú–¼", "ì¬ŽÒ", "“à—e"};
        Object[][] data = new Object[cnt][4];
        //===========================
        
        LDAPEntry entry = null;
        String baseDN = null;
        int k = 0;
        while (results.hasMoreElements()) {
            try {
                entry = (LDAPEntry)results.next();
                baseDN = entry.getDN();
                if (false == hasChildren(baseDN)) {                    
                    LDAPAttributeSet findAttrs = entry.getAttributeSet();
                    Enumeration enumAttrs = findAttrs.getAttributes();
                    while ( enumAttrs.hasMoreElements()) {
                       LDAPAttribute anAttr = (LDAPAttribute)enumAttrs.nextElement();
                       String attrName = anAttr.getName();
                       
                       // get the first value of the attribute
                       Enumeration enumVals = anAttr.getStringValues();
                       String aVal = "";
                       if (enumVals != null) {
                          if ( enumVals.hasMoreElements() ) {
                            aVal = (String)enumVals.nextElement();
                          }
                       }
                       
                       if (attrName.equals("uid")) {
                           data[k][0] = baseDN;//aVal;
                       } else if (attrName.equals("cn")) {
                           data[k][1] = aVal;
                       } else if (attrName.equals("sn")) {
                           data[k][2] = aVal;
                       } else if (attrName.equals("description")) {
                           data[k][3] = aVal;
                       }
                    }
                    
                    ++k;
                }
            } catch (LDAPException e) {
                return;
            }
        }
        
        //===========================
        if (table != null) {
            table.removeAll();
        }
        table = new JTable(data, columnNames);
        table.setEnabled(true);
        jScrollPane3.setViewportView(table);
        
        table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting() == false) {
                    int[] selectedRow = table.getSelectedRows();
                    String selectedDN = "";
                    if (selectedRow.length > 0) {
                        selectedDN = (String)table.getValueAt(selectedRow[0], 0);/////
                    }

                    System.out.println("calling readContents from valueChanged of the table.");
                    System.out.println(selectedDN);
                    readContents(selectedDN);
                }
            }
        });
        //===========================
    }

    public void traverseTopDirectory(String dn) {
        // get connection
        LDAPConnection ld = getConnection();
        if (ld == null) {
            System.out.println("*** Couldn't search DN. Connection is null.");
            return;
        }
        
        String[] attrs = null;
        LDAPSearchResults results = null;
        try {
            results = ld.search(dn, netscape.ldap.LDAPConnection.SCOPE_BASE, "(objectclass=*)", attrs, false);
        } catch (LDAPException e) {
            System.out.println("*** Directory was not found.");
            return;
        }
        
        if ( results.hasMoreElements() == false ) {
            System.out.println("*** Directory was not found.");
            return;
        }
        
        LDAPEntry entry = null;
        String baseDN = null;
        //while ( results.hasMoreElements() ) { 
            try {
                entry = (LDAPEntry)results.next();
                baseDN = entry.getDN();
                System.out.println("Level " + level + " ---- " + baseDN);
                
                //-------------------------------------------
                root = new DefaultMutableTreeNode(baseDN);
                currNode = root;
                //
                if (tree != null) {
                    tree.removeAll();
                    tree = null;
                }
                tree = new JTree(root);
                jScrollPane1.setViewportView(tree);
                tree.addTreeSelectionListener(new TreeSelectionListener() {
                    public void valueChanged(TreeSelectionEvent se) {
                        JTree aTree = (JTree)se.getSource();
                        DefaultMutableTreeNode selected = (DefaultMutableTreeNode)aTree.getLastSelectedPathComponent();
                        String selectedName = selected.toString();
                        //System.out.println("Selected Level: " + selected.getLevel());
                        System.out.println("Selected: " + selectedName);
                        
                        // check level in the tree
                        if ( selected.getLevel() > 0 ) {
                            // pass the selected DN and get attributes
                            int i = selectedName.indexOf("<>");
                            if (i > 0) {
                                selectedName = selectedName.substring(i + 2, selectedName.length());
                            }
                            readEntry(selectedName);
                            
                            System.out.println(" <><> ");
                            
                            readLeaves(selectedName);
                        } else {
                            
                            readEntry(selectedName);                            
                            
                            if (table != null) {
                                table.removeAll();
                                table = null;
                            }
                            jScrollPane3.setViewportView(null);
                        }
                        
                        jLabel2.setText("");
                    }
                });
                //-------------------------------------------
                
                printStringValues(entry);
                ++level;
                traverseDirectory(baseDN);
                --level;
                
            } catch (LDAPException e) {
                System.out.println("*** Couldn't get entry of search result.");
                return;
            }
        //}
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0); 
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new LDAPViewer().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private jp.ac.kumamoto_u.kuh.fc.jsato.swing_beans.LDAPLoginBean lDAPLoginBean1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
