/*
 * SchemaStockFrame.java
 *
 * Created on 2002/06/20, 6:59
 */

package jp.ac.kumamoto_u.kuh.fc.jsato.swing_beans;

import javax.swing.*;
import javax.swing.event.*;

import open.dolphin.client.*;
import open.dolphin.exception.PluginException;
import open.dolphin.plugin.*;

import java.awt.*;
import java.beans.*;

/**
 *
 * @author  Junzo SATO
 */
public class SchemaStockFrame extends javax.swing.JFrame implements IMainWindowPlugin { 
    
    String id;
    String name;
    boolean isSchemaStockTableLDAPCreated = false;
    SchemaStockTableLDAP stockTableLDAP;

    /** Creates new form SchemaStockFrame */
    public SchemaStockFrame() {
    }
    
    public String getName() {
        return id;
    }
    
    public void setName(String val) {
        id = val;
    }      
    
    public String getTitle() {
        return name;
    }
    
    public void setTitle(String val) {
        name = val;
    }
    
    public void init() throws PluginException {
    }
    
    public void vetoableChange(PropertyChangeEvent e) throws PropertyVetoException {
    }
    
    public void propertyChange(PropertyChangeEvent e) {
        
        String prop = e.getPropertyName();
        if (prop.equals("loginProp")) {
            boolean b = ((Boolean)e.getNewValue()).booleanValue();
            setVisible(b);
        }
        else if (prop.equals("exitProp")) {
            boolean b = ((Boolean)e.getNewValue()).booleanValue();
            if (b) {
                exitForm(null);
            }
        }
    }    
    
    public void stop() {
        exitForm(null);
    }
    
    public void showUI() {
        setVisible(true);
    }
    
    public void start() {
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int)screen.getWidth() - this.getWidth();
        setLocation(x, 20);
        setVisible(true);
        
       //-----------------------------------------------------------------------------
        //
        //String schemaFolder = "c:/dolphin/Schema";
        //String schemaFolder = DolphinContext.getSchemaDirectory();
        //System.out.println(schemaFolder);
        //SchemaStockTable tbl = new SchemaStockTable(schemaFolder);
        jTabbedPane1.addTab(new String("基本セット"), new SchemaStockTableDefault());
        //-----------------------------------------------------------------------------
        //
        //SchemaStockTableLDAP stockTableLDAP = new SchemaStockTableLDAP();
        jTabbedPane1.addTab(new String("共有"), null);
        //-----------------------------------------------------------------------------                  
        jTabbedPane1.addTab(new String("個人用"), new SchemaStockTable());
        //pack();
        
        jTabbedPane1.addChangeListener(new ChangeListener() {
            int selectedIndex = -1;
            JTabbedPane tp;
            public void stateChanged(ChangeEvent ce) {
                tp = (JTabbedPane)ce.getSource();
                selectedIndex = tp.getSelectedIndex();
                //System.out.println(selectedIndex);
                if (selectedIndex == 1 &&
                    isSchemaStockTableLDAPCreated == false) {
                    //System.out.println("Should create panel...");
                    //-----------------------------------------------------------------------------
                    //
                    //jTabbedPane1.addTab(new String("共有"), new SchemaStockTableLDAP());
                    //-----------------------------------------------------------------------------                  
                    // if creating the pane was succeeded,
                    // the flag should be set to true...
                    stockTableLDAP = new SchemaStockTableLDAP();
                    tp.setComponentAt(1, stockTableLDAP);
                    isSchemaStockTableLDAPCreated = true;
                }
                Component cp = tp.getSelectedComponent();
                //System.out.println(cp.toString());
                
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("\u30b7\u30a7\u30fc\u30de\u30d6\u30e9\u30a6\u30b6");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 680));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(400, 680));
        getContentPane().add(jTabbedPane1);

        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.out.println("Exit form");
        if (stockTableLDAP != null) {
            stockTableLDAP.disconnectLDAP();
        }
        setVisible(false);
        dispose();
        ClientContext.remove(SchemaStockFrame.this);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //new SchemaStockFrame().show();
        new SchemaStockFrame().start();
    }
    
    // 変数宣言 - 編集不可//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // 変数宣言の終わり//GEN-END:variables

}