/*
 * StatusBean.java
 *
 * Created on 2001/08/23, 14:50
 */

package jp.ac.kumamoto_u.kuh.fc.jsato.swing_beans;

import javax.swing.*;
import java.util.Date;
/**
 *
 * @author  Junzo SATO
 * @copyright   Copyright (c) 2001, Junzo SATO. All rights reserved.
 */

public class StatusBean extends javax.swing.JPanel {

    /** Creates new form StatusBean */
    public StatusBean() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        pnScroll = new javax.swing.JScrollPane();
        taStatus = new javax.swing.JTextArea();
        
        setLayout(new java.awt.BorderLayout());
        
        pnScroll.setPreferredSize(new java.awt.Dimension(400, 300));
        pnScroll.setViewportView(taStatus);
        
        add(pnScroll, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    /** Getter for property taStatus.
     * @return Value of property taStatus.
 */
    public JTextArea getTaStatus() {
        return taStatus;
    }    

    public void printlnStatus(String str) {
	Date date = new Date();
	if (date != null)
	{
	    taStatus.append(date.toString() + ": " + str + "\n");
	} else {
	    taStatus.append(str + "\n");
	}
    }
    
    public void printStatus(String str) {
	Date date = new Date();
	if (date != null)
	{
	    taStatus.append(date.toString() + ": " + str);
	} else {
	    taStatus.append(str);
	}
    }

    public void printlnStatus(String str, boolean b) {
	taStatus.append(str + "\n");
    }
    
    public void printStatus(String str, boolean b) {
	taStatus.append(str);
    }
    
    public void clearStatus() {
        taStatus.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane pnScroll;
    private javax.swing.JTextArea taStatus;
    // End of variables declaration//GEN-END:variables

}
