/*
 * XSLT.java
 *
 * Created on 2001/12/24, 18:29
 */

package jp.ac.kumamoto_u.kuh.fc.jsato.xslt;

/**
 *
 * @author  Junzo SATO
 * @version 
 *
 * This class was created based on the Stylizer example from java.sun.com
 */

import java.io.*;
import java.net.*;
import javax.swing.*;
import java.awt.*;

import open.dolphin.client.*;
import open.dolphin.util.MMLDate;

import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.FactoryConfigurationError;
import javax.xml.parsers.ParserConfigurationException;
 
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;
import org.w3c.dom.Document;
import org.w3c.dom.DOMException;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamSource;
import javax.xml.transform.stream.StreamResult;

//-------------------------------------------------------

import jp.ac.kumamoto_u.kuh.fc.jsato.*;

public class XSLT {
    /*
    static URL urlXSL;
    
    static {
        try {
            urlXSL = jp.ac.kumamoto_u.kuh.fc.jsato.xslt.XSLT.class.getResource(
                "MmlStylesheetForJava.xsl"
            );
        } catch (Exception ignored) {
            
        }
    }
     */

    static public String xslFile = "/jp/ac/kumamoto_u/kuh/fc/jsato/xslt/MmlStylesheetForJava.xsl";
    static public String toHTML(Document document) {
        StringWriter sw = null;
        try {
            // Use a Transformer for output
            TransformerFactory tFactory = TransformerFactory.newInstance();

            // load stylesheet
            //File stylesheet = new File(urlXSL.getPath());
            //StreamSource stylesource = new StreamSource(stylesheet);
            InputStream in = jp.ac.kumamoto_u.kuh.fc.jsato.xslt.XSLT.class.getResourceAsStream(
                xslFile
            );
            StreamSource stylesource = new StreamSource(in);
            
            Transformer transformer = tFactory.newTransformer(stylesource);
 
            // apply stylesheet to the xml document ============================
            DOMSource source = new DOMSource(document);
            StreamResult result = new StreamResult();
            sw = new StringWriter();
            result.setWriter(sw);
            transformer.transform(source, result);
            //==================================================================
            
            in.close();
            
        } catch (TransformerConfigurationException tce) {
           // Error generated by the parser
           System.out.println ("Transformer Factory error");
           System.out.println("   " + tce.getMessage());

           // Use the contained exception, if any
           Throwable x = tce;
           if (tce.getException() != null)
               x = tce.getException();
           x.printStackTrace();
      
        } catch (TransformerException te) {
           // Error generated by the parser
           System.out.println ("Transformation error");
           System.out.println("   " + te.getMessage() );

           // Use the contained exception, if any
           Throwable x = te;
           if (te.getException() != null)
               x = te.getException();
           x.printStackTrace();
           
        } catch(IOException ioe) {
           System.out.println ("I/O error");
           System.out.println("   " + ioe.getMessage() );
        }
        
        String htmlString = "";
        //try {
        //    System.out.println("--------------- CONVERTING --------------");
        //    htmlString = new String(sw.getBuffer().toString().getBytes(),"SJIS");
        //} catch (Exception e) {
            htmlString = new String(sw.getBuffer().toString());
        //}
        
        try {
            if (sw != null)
                sw.close();
        } catch (IOException ioe) {
           // I/O error
           ioe.printStackTrace();
        }
        
        return htmlString;
    }
    
    static public String toHTML(String xmlString) {
        Document document = null;
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(true);
            factory.setIgnoringComments(true);
            //factory.setValidating(true);

            DocumentBuilder builder = factory.newDocumentBuilder();
            // load xml document
            document = builder.parse(new InputSource(new StringReader(xmlString)));
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception  x = sxe;
            if (sxe.getException() != null)
               x = sxe.getException();
            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
        return toHTML(document);
    }
    
    static public String toHTML(File xmlFile) {
        /*
        Document document = null;
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(true);
            factory.setIgnoringComments(true);
            //factory.setValidating(true);
            
            DocumentBuilder builder = factory.newDocumentBuilder();
            
            // load xml document
            document = builder.parse(xmlFile);
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception  x = sxe;
            if (sxe.getException() != null)
               x = sxe.getException();
            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
        return toHTML(document);
        */
        
        StringWriter sw = null;
        try {
            // Use a Transformer for output
            TransformerFactory tFactory = TransformerFactory.newInstance();

            // load stylesheet
            //File stylesheet = new File(urlXSL.getPath());
            //StreamSource stylesource = new StreamSource(stylesheet);
            InputStream in = jp.ac.kumamoto_u.kuh.fc.jsato.xslt.XSLT.class.getResourceAsStream(
                xslFile
            );
            StreamSource stylesource = new StreamSource(in);
            StreamSource source = new StreamSource(xmlFile);
            
            Transformer transformer = tFactory.newTransformer(stylesource);
 
            // apply stylesheet to the xml source ==============================
            StreamResult result = new StreamResult();
            sw = new StringWriter();
            result.setWriter(sw);
            transformer.transform(source, result);
            //==================================================================
            
            in.close();
            
        } catch (TransformerConfigurationException tce) {
           // Error generated by the parser
           System.out.println ("Transformer Factory error");
           System.out.println("   " + tce.getMessage());

           // Use the contained exception, if any
           Throwable x = tce;
           if (tce.getException() != null)
               x = tce.getException();
           x.printStackTrace();
      
        } catch (TransformerException te) {
           // Error generated by the parser
           System.out.println ("Transformation error");
           System.out.println("   " + te.getMessage() );

           // Use the contained exception, if any
           Throwable x = te;
           if (te.getException() != null)
               x = te.getException();
           x.printStackTrace();
           
        } catch(IOException ioe) {
           System.out.println ("I/O error");
           System.out.println("   " + ioe.getMessage() );
        }
        
        String htmlString = "";
        //try {
        //    System.out.println("--------------- CONVERTING --------------");
        //    htmlString = new String(sw.getBuffer().toString().getBytes(),"SJIS");
        //} catch (Exception e) {
            htmlString = new String(sw.getBuffer().toString());
        //}
        
        try {
            if (sw != null)
                sw.close();
        } catch (IOException ioe) {
           // I/O error
           ioe.printStackTrace();
        }
        
        return htmlString;
    }
    
    //==========================================================================
    static public String getBodyContent(String htmlString) {
       // because JEditorPane cannot handle complex header, 
       // passing only the contents of the body to the JEditorPane is important
       //       
       int index = htmlString.indexOf("<body>");
       int index2 = htmlString.indexOf("</body>");
       try {
            return htmlString.substring(index + 6, index2 - 1);
       } catch (Exception e) {
            // in case of an error such as 'index out of range', empty string is returned:-)
            return "";
       }
    }
    //==========================================================================
    
    static public JEditorPane createHTMLPane(String xmlString) {
        String htmlString = XSLT.toHTML(xmlString);
        //=======================================================================
        htmlString = XSLT.getBodyContent(htmlString);
        //=======================================================================
        JEditorPane ep = new JEditorPane("text/html", htmlString);
        //JEditorPane ep = new JEditorPane("text/html", "<html><tt><basefont size='1'>" + htmlString + "</tt></html>");
        return ep;
    }
    
    static public JEditorPane createHTMLPane(File xmlFile) {
        String htmlString = XSLT.toHTML(xmlFile);
        //=======================================================================
        htmlString = XSLT.getBodyContent(htmlString);
        //=======================================================================
        JEditorPane ep = new JEditorPane("text/html", htmlString);
        //JEditorPane ep = new JEditorPane("text/html", "<html><tt><basefont size='1'>" + htmlString + "</tt></html>");
        return ep;
    }
    
    /** Creates new XSLT */
    protected XSLT() {
    }

    /**
    * @param args the command line arguments
    */
    
    static public JFrame showInFrame(JEditorPane ep) {
        try {
            // Let's try to display created HTML file.
            JFrame frame = new JFrame();
            JScrollPane scroll = new JScrollPane();
            frame.getContentPane().add(scroll);
            scroll.setViewportView(ep);
            frame.setVisible(true);
            scroll.setPreferredSize(new Dimension(600,700));
            frame.pack();
            //frame.setTitle("XSLT");
            return frame;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }    
    }
    
    public static void ShowEditorPaneInFrame(String pathname) {
        try {
            JEditorPane pane = new JEditorPane();
            HyperlinkHandler hh = new HyperlinkHandler(pane);
            File f = new File(pathname);
            hh.ReadFile(f);
            JFrame fr = XSLT.showInFrame(pane);
            if (fr != null) fr.setTitle(pathname);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void ShowSimpleEditorPaneInFrame(URL url) {
        try {
            JEditorPane pane = new JEditorPane(url);
            JFrame fr = XSLT.showInFrame(pane);
            if (fr != null) fr.setTitle(url.getPath());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /*
        File xmlFile = new File("c:/mmlLb/0c6c3e80-10a4-445b-845a-6a9c83b52003.xml");
        JEditorPane ep = XSLT.createHTMLPane(xmlFile);
        XSLT.showInFrame(ep);
         */
        
        /*
        String xmlString = "<?xml version='1.0' encoding='Shift_JIS'?><Mml><MmlHeader></MmlHeader></Mml>";
        JEditorPane ep2 = XSLT.createHTMLPane(xmlString);
        XSLT.showInFrame(ep2);
         */
        
        //============================
        //xslFile = "/jp/ac/kumamoto_u/kuh/fc/jsato/xslt/MyMMLStyle.xsl";
        
        try {
            // Here is another test which uses HyperlinkHandler.
            //File xmlFile = new File("c:/mmlLb/0c6c3e80-10a4-445b-845a-6a9c83b52003.xml");
            //File xmlFile = new File("/SampleInstance/real/JPN432010100018-LBTSTLB0001-00036528200203080803.xml");
            File xmlFile = new File("/DOLPHIN_PROJECT_MATERIALS/SampleInstance/real/JPN432010100018-LBTSTLB0001-00036528200203080803.xml");
            String htmlString = XSLT.toHTML(xmlFile);
            
            htmlString = XSLT.getBodyContent(htmlString);            
            
            htmlString = "<html><head></head><body>" + htmlString + "</body></html>";
            System.out.println(htmlString);

            String name = new String(MMLDate.getDateTime() + ".htm").replaceAll(":", "");

            String pathname = ClientContext.getUserDirectory() + File.separator + name;
            
            FileUtils.toFile(pathname, htmlString);
            
            //String pn = ClientContext.getInstalledDirectory() + File.separator + "test.htm";
            //ShowEditorPaneInFrame(pn);
            
            ShowEditorPaneInFrame(pathname);
            //ShowSimpleEditorPaneInFrame(new URL(pathname));
        } catch (Exception e) {
            
        }
        
        /*
        try {
            ShowSimpleEditorPaneInFrame(new URL("http://www.apple.com"));
        } catch (Exception e) {
            
        }
         */
        //============================
        
        /*
        String keyword = "[外部参照あり]";
        String s = "外部参照あり[外部参照あり]なしabc[外部参照あり]あり";
        StringBuffer sb = new StringBuffer(s);
        int start = -1, end = -1;
        while (true) {
            start = s.indexOf(keyword);
            if (start < 0) break;
            
            end = start + keyword.length();
            sb.replace(start, end, "<img src=lalala");
            s = sb.toString();
            System.out.println(s);
            start = -1;
            end = -1;
        }
         */
    }
}
