/*
 * LetterView2.java
 *
 * Created on 2008/01/30, 21:42
 */

package open.dolphin.letter;

import open.dolphin.client.Panel2;

/**
 *
 * @author  kazm
 */
public class LetterView extends Panel2 {
    
    /** Creates new form LetterView2 */
    public LetterView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        consultantHospital = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        consultantDept = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        consultantDoctor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        patientGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patientBirthday = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        patientAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        disease = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        purpose = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clinicalCourse = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        medication = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        remarks = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pastFamily = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        confirmed = new javax.swing.JTextField();
        atesakiLbl = new javax.swing.JLabel();

        jLabel1.setText("診療情報提供書（フォーム）"); // NOI18N

        jLabel2.setText("紹介先医療機関名:"); // NOI18N

        consultantHospital.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel3.setText("紹介先診療科:"); // NOI18N

        consultantDept.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel4.setText("紹介先先生:"); // NOI18N

        consultantDoctor.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        consultantDoctor.setToolTipText("設定の紹介状等で、敬称を選択できます"); // NOI18N

        jLabel5.setText("患者氏名:"); // NOI18N

        patientName.setEditable(false);
        patientName.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel6.setText("性別:"); // NOI18N

        patientGender.setEditable(false);
        patientGender.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel7.setText("生年月日:"); // NOI18N

        patientBirthday.setEditable(false);
        patientBirthday.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel8.setText("年齢:"); // NOI18N

        patientAge.setEditable(false);
        patientAge.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel9.setText("傷病名:"); // NOI18N

        disease.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel10.setText("紹介目的:"); // NOI18N

        purpose.setFont(new java.awt.Font("SansSerif", 0, 12));

        jLabel11.setText("既往歴/家族歴:"); // NOI18N

        jLabel12.setText("症状経過:"); // NOI18N

        clinicalCourse.setColumns(20);
        clinicalCourse.setFont(new java.awt.Font("SansSerif", 0, 12));
        clinicalCourse.setLineWrap(true);
        clinicalCourse.setRows(5);
        jScrollPane2.setViewportView(clinicalCourse);

        jLabel13.setText("検査結果:"); // NOI18N

        jLabel14.setText("治療経過:"); // NOI18N

        jLabel15.setText("現在の処方:"); // NOI18N

        medication.setColumns(20);
        medication.setFont(new java.awt.Font("SansSerif", 0, 12));
        medication.setLineWrap(true);
        medication.setRows(5);
        jScrollPane3.setViewportView(medication);

        jLabel16.setText("備考:"); // NOI18N

        remarks.setFont(new java.awt.Font("SansSerif", 0, 12));

        pastFamily.setColumns(20);
        pastFamily.setFont(new java.awt.Font("SansSerif", 0, 12));
        pastFamily.setLineWrap(true);
        pastFamily.setRows(5);
        jScrollPane1.setViewportView(pastFamily);

        jLabel19.setText("年月日:"); // NOI18N

        confirmed.setEditable(false);
        confirmed.setFont(new java.awt.Font("SansSerif", 0, 12));

        atesakiLbl.setText("先生　御机下"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel19)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel9)
                            .add(jLabel11)
                            .add(jLabel7)
                            .add(jLabel10)
                            .add(jLabel15)
                            .add(jLabel12)
                            .add(jLabel13)
                            .add(jLabel14)
                            .add(jLabel16))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, remarks)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, consultantDoctor)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, consultantDept, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, patientName)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, patientBirthday))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(atesakiLbl)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel6)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(patientGender))
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel8)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(patientAge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(consultantHospital, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane3)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, purpose)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, disease, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(212, 212, 212)
                        .add(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel19)
                    .add(confirmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(consultantHospital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(consultantDept, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(consultantDoctor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(atesakiLbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(patientName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(patientGender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientBirthday, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(jLabel7)
                    .add(patientAge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(disease, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(purpose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel11)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel14))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel15)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(remarks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atesakiLbl;
    private javax.swing.JTextArea clinicalCourse;
    private javax.swing.JTextField confirmed;
    private javax.swing.JTextField consultantDept;
    private javax.swing.JTextField consultantDoctor;
    private javax.swing.JTextField consultantHospital;
    private javax.swing.JTextField disease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea medication;
    private javax.swing.JTextArea pastFamily;
    private javax.swing.JTextField patientAge;
    private javax.swing.JTextField patientBirthday;
    private javax.swing.JTextField patientGender;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField purpose;
    private javax.swing.JTextField remarks;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getConsultantDept() {
        return consultantDept;
    }

    public javax.swing.JTextField getConsultantDoctor() {
        return consultantDoctor;
    }

    public javax.swing.JTextField getConsultantHospital() {
        return consultantHospital;
    }

    public javax.swing.JTextArea getClinicalCourse() {
        return clinicalCourse;
    }

    public javax.swing.JTextField getConfirmed() {
        return confirmed;
    }

    public javax.swing.JTextField getDisease() {
        return disease;
    }

    public javax.swing.JTextArea getMedication() {
        return medication;
    }

    public javax.swing.JTextArea getPastFamily() {
        return pastFamily;
    }

    public javax.swing.JTextField getPatientAge() {
        return patientAge;
    }

    public javax.swing.JTextField getPatientBirthday() {
        return patientBirthday;
    }

    public javax.swing.JTextField getPatientGender() {
        return patientGender;
    }

    public javax.swing.JTextField getPatientName() {
        return patientName;
    }

    public javax.swing.JTextField getPurpose() {
        return purpose;
    }

    public javax.swing.JTextField getRemarks() {
        return remarks;
    }

    public javax.swing.JLabel getAtesakiLbl() {
        return atesakiLbl;
    }
}
